# New TravisCI infrastructure (Ubuntu 14.04)
sudo: required
dist: trusty
language: python
python:
  - "2.7"
before_install:
    - sudo apt-get update -q
    - sudo apt-get install -qy libpcap-dev netcat
install: 
  - sh -c "sudo python setup.py install"
script: 
  - sh -c "sudo python setup.py test"
after_failure:
  - sh -c "cat test.log"
