language: python
python:
  - "2.7"
before_install:
    - sudo apt-get install libpcap-dev python-dev python-pip netcat
install: 
  - sh -c "sudo python setup.py install"
script: 
  - sh -c "sudo python setup.py test"
after_failure:
  - sh -c "cat test.log"
