language: python
python:
  - "2.7"
before_install:
  - sudo apt-get install libpcap-dev
install: 
  - sh -c "cd drums-core && python setup.py install"
script: 
  - sh -c "cd drums-core && sudo python setup.py test"
